name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/train_pca.csv"
  TARGET_VAR: "Credit_Score"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Ambil kode dari Repo
      - uses: actions/checkout@v3

      # 2. Setup Python sesuai materi 
      - name: Set up Python 3.13.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.9"

      # 3. Cek Environment Variables (Debugging)
      - name: Check Env
        run: |
          echo $CSV_URL

      # 4. Install MLflow dan update pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # 5. Jalankan MLflow Project
      # PENTING: Pastikan file MLproject dan conda.yaml ada di repo Anda!
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local

      # 6. Ambil Run ID terbaru secara otomatis
      # Script ini mencari folder terbaru di mlruns/0/
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      # 7. Build Docker Image menggunakan MLflow
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "cc"

      # 8. Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 9. Tag Image agar sesuai format Docker Hub (username/repo:tag)
      - name: Tag Docker Image
        run: |
          docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest

      # 10. Push Image ke Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest